# -*- coding: utf-8 -*-
# vim: ft=yaml
---
prometheus:
  archive:
    dir: /opt/prometheus
    uri: https://github.com/prometheus
    suffix: tar.gz
    kwargs:
      trim_output: True
      enforce_toplevel: True
      archive_format: tar
      retry:
        attempts: 3
        until: True
        interval: 60
        splay: 10
    binaries:
      prometheus:
        - prometheus
        - promtool
      alertmanager:
        - amtool
        - alertmanager
      blackbox_exporter:
        - blackbox_exporter
      consul_exporter:
        - consul_exporter
      graphite_exporter:
        - graphite_exporter
      haproxy_exporter:
        - haproxy_exporter
      memcached_exporter:
        - memcached_exporter
      mysqld_exporter:
        - mysqld_exporter
      node_exporter:
        - node_exporter
      pushgateway:
        - pushgateway
      statsd_exporter:
        - statsd_exporter
      
    versions:
      prometheus: '2.10.0'
      alertmanager: '0.17.0'
      blackbox_exporter: '0.14.0'
      consul_exporter: '0.4.0'
      graphite_exporter: '0.6.2'
      haproxy_exporter: '0.10.0'
      memcached_exporter: '0.5.0'
      mysqld_exporter: '0.11.0'
      node_exporter: '0.18.1'
      pushgateway: '0.8.0'
      statsd_exporter: '0.11.2'
    hashes:
      prometheus: f4233783826f18606b79e5cef0686e4a9c2030146a3c7ce134f0add09f5adcb7
      alertmanager: 7c8d2cfeb021c80881ae9904d959131091b8785b6fda9800f84ddef148fe0a4f 
      blackbox_exporter: a2918a059023045cafb911272c88a9eb83cdac9a8a5e8e74844b5d6d27f19117
      consul_exporter: ff77c03de67cf381f67480b5be6699901785a34145c518c3484ae3e5b8440d08
      graphite_exporter: 9b962bd06406ece4a865ad6947a6e652e48a92a0d77e496a0351c04e9c2c5e9e
      haproxy_exporter: 08150728e281f813a8fcfff4b336f16dbfe4268a1c7510212c8cff2579b10468
      memcached_exporter: bb07f496ceb63dad9793ad4295205547a4bd20b90628476d64fa96c9a25a020f
      mysqld_exporter: b53ad48ff14aa891eb6a959730ffc626db98160d140d9a66377394714c563acf
      node_exporter: b2503fd932f85f4e5baf161268854bf5d22001869b84f00fd2d1f57b51b72424
      pushgateway: 6949866ba9ad0cb88d3faffd4281f17df79281398b4dbd0ec3aab300071681ca
      statsd_exporter: 4632ad0c5552e271e84c376da3ffe3af8c265ec5c3035334b70e35756aca1906
