# -*- coding: utf-8 -*-
# vim: ft=yaml
---
prometheus:
  pkg:
    name: prometheus
    use_upstream_archive: False

  rootgroup: root
  kernel: {{ grains.kernel | lower }}
  config_file: /etc/prometheus/prometheus.yml
  config: {}
  environ_file: /etc/default/prometheus.sh
  environ: []
  service:
    name: prometheus
    user: prometheus
    group: prometheus
  exporters:
    node:
      pkg:
        name: prometheus-node-exporter
      service: prometheus-node-exporter

  linux:
    #'Alternatives system' priority: zero disables (default)
    altpriority: 0

  archive:
    # see ./archive/default.yaml
    wanted:
      - prometheus
      - alertmanager
      - node_exporter
